### ISSUE TITLE
ユーザ管理機能を追加する

### ISSUE THREAD

**Issue by takanori-matsumoto-mulodo** [hank-ehly-mulodo/l5todo_dev#1]
### 新規ユーザを作成する
 - [x] 右上のRegisterボタンから、新規ユーザ登録画面に遷移する
 - [x] 登録画面では、ユーザ名とパスワードを入力して、新規ユーザを作成することができる

### ログインする
 - [x] 右上のLoginボタンから、ログイン画面に遷移する
 - [x] 登録済みのユーザが、正しいユーザ名とパスワードを入力すると、ログインできる

### ログアウトする
 - [x] 画面上部のメニューバーにLogoutボタンを追加する
 - [x] Logoutボタンを押すと、Logoutする

**Comment by takanori-matsumoto-mulodo** [comment]
不明な点があれば、何でも聞いてください。

**Comment by hank-ehly-mulodo** [comment]
新規Laravelプロジェクトを作成するとユーザ管理機能が既に組み込まれているみたいなので、削除して自分で作り直しますが、その仕様で問題ないでしょうか？

**Comment by takanori-matsumoto-mulodo** [comment]
すみません。私の勘違いでした。
上記の機能は既に備わっていましたね。
組み込まれている機能を、そのまま使用してもOKです。
このIssueはCloseしちゃいます。

新しいIssueを作成するので、そちらに取り組んでください。

**Comment by hank-ehly-mulodo** [comment]
新しいIssueをありがとうございます。
管理機能を自分なりに作り直しましたが、
ソースコードをご確認頂けないでしょうか？

**Comment by hank-ehly-mulodo** [comment]
ユーザ管理機能＊

**Comment by takanori-matsumoto-mulodo** [comment]
OKです。
正しく動いていると思います。
